### ISSUE TITLE
Unable to find optparse

### ISSUE THREAD

**Issue by rmenn** [sroegner/zookeeper-util#3]
Hi,

We just tried to use this tool and we couldn't because the optparse gem is no longer available upstream. Are you still using this ? Any suggestions on how to get it working?

**Comment by sroegner** [comment]
Hi,

no I am not actively maintaining or using this any longer - maybe this is a good time to let it die for good.
I think it was too limited in its abilities from the start and for a (java) programmer it should be a rather quick exercise to built something sufficiently similar or better using curator.

Sorry,
Steffen

**Comment by sroegner** [comment]
looks like jruby changed on us - might be worth a look

**Comment by sroegner** [comment]
Ok, if I use jruby.jar from within the jruby tarball then I see the same require error - HOWEVER using jruby-complete.jar as documented (current version is here http://jruby.org.s3.amazonaws.com/downloads/1.7.13/jruby-complete-1.7.13.jar) it will work.

hth
Steffen
